### ISSUE TITLE
DB Dump

### ISSUE THREAD

**Issue by eddeo93** [thefuntastic/kickstarter-rewards-tool#1]
Hi,

First of all, thank you so much for sharing this scraper. I am working on a research paper on crowdfunding and I need as much data as I can. However, my coding skills are limited,and I am having some hard time using this git. I saw that you had a Kickscrape DB Dump with over 87,000+ projects. Can you please convert that into a .csv or excel file and share it with me? That will really make my life easier. Thank you so much.

Eddie

**Comment by thefuntastic** [comment]
Hi eddeo93, unfortunately this scraper is not nearly as hardcore as that. You must have it mistaken for another project. I certainly don't have a DB with 87000 projects. Good luck finding what you need. ;)

**Comment by eddeo93** [comment]
hey thefuntastic, I am just trying to consolidate any data on crowdfunding out there for my research, so if you have any data that you can share with me, that would be awesome. We are trying to create an open source version of all crowdfunding data. Your help will be greatly appreciated it.
